name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_1word_query_10points
      id: test_1word_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_query_10points
        setup-command: pip install pytest
        command: pytest -k test_1word_query_10points
        timeout: 10
        max-score: 10
    - name: test_1word_repeated1_query_10points
      id: test_1word_repeated1_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_repeated1_query_10points
        setup-command: ''
        command: pytest -k test_1word_repeated1_query_10points
        timeout: 10
        max-score: 10
    - name: test_1word_repeated2_query_10points
      id: test_1word_repeated2_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_repeated2_query_10points
        setup-command: ''
        command: pytest -k test_1word_repeated2_query_10points
        timeout: 10
        max-score: 10
    - name: test_1word_unknown_query_10points
      id: test_1word_unknown_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_unknown_query_10points
        setup-command: ''
        command: pytest -k test_1word_unknown_query_10points
        timeout: 10
        max-score: 10
    - name: test_1word_infrequent_query_10points
      id: test_1word_infrequent_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_infrequent_query_10points
        setup-command: ''
        command: pytest -k test_1word_infrequent_query_10points
        timeout: 10
        max-score: 10
    - name: test_2words_query_10points
      id: test_2words_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_2words_query_10points
        setup-command: ''
        command: pytest -k test_2words_query_10points
        timeout: 10
        max-score: 10
    - name: test_2words_reversed_query_10points
      id: test_2words_reversed_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_2words_reversed_query_10points
        setup-command: ''
        command: pytest -k test_2words_reversed_query_10points
        timeout: 10
        max-score: 10
    - name: test_1word_infrequent_query1_10points
      id: test_1word_infrequent_query1_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_infrequent_query1_10points
        setup-command: ''
        command: pytest -k test_1word_infrequent_query1_10points
        timeout: 10
        max-score: 10
    - name: test_1word_infrequent_query2_10points
      id: test_1word_infrequent_query2_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1word_infrequent_query2_10points
        setup-command: ''
        command: pytest -k test_1word_infrequent_query2_10points
        timeout: 10
        max-score: 10
    - name: test_2words_infrequent_query_10points
      id: test_2words_infrequent_query_10points
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_2words_infrequent_query_10points
        setup-command: ''
        command: pytest -k test_2words_infrequent_query_10points
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_1WORD_QUERY_10POINTS_RESULTS: "${{steps.test_1word_query_10points.outputs.result}}"
        TEST_1WORD_REPEATED1_QUERY_10POINTS_RESULTS: "${{steps.test_1word_repeated1_query_10points.outputs.result}}"
        TEST_1WORD_REPEATED2_QUERY_10POINTS_RESULTS: "${{steps.test_1word_repeated2_query_10points.outputs.result}}"
        TEST_1WORD_UNKNOWN_QUERY_10POINTS_RESULTS: "${{steps.test_1word_unknown_query_10points.outputs.result}}"
        TEST_1WORD_INFREQUENT_QUERY_10POINTS_RESULTS: "${{steps.test_1word_infrequent_query_10points.outputs.result}}"
        TEST_2WORDS_QUERY_10POINTS_RESULTS: "${{steps.test_2words_query_10points.outputs.result}}"
        TEST_2WORDS_REVERSED_QUERY_10POINTS_RESULTS: "${{steps.test_2words_reversed_query_10points.outputs.result}}"
        TEST_1WORD_INFREQUENT_QUERY1_10POINTS_RESULTS: "${{steps.test_1word_infrequent_query1_10points.outputs.result}}"
        TEST_1WORD_INFREQUENT_QUERY2_10POINTS_RESULTS: "${{steps.test_1word_infrequent_query2_10points.outputs.result}}"
        TEST_2WORDS_INFREQUENT_QUERY_10POINTS_RESULTS: "${{steps.test_2words_infrequent_query_10points.outputs.result}}"
      with:
        runners: test_1word_query_10points,test_1word_repeated1_query_10points,test_1word_repeated2_query_10points,test_1word_unknown_query_10points,test_1word_infrequent_query_10points,test_2words_query_10points,test_2words_reversed_query_10points,test_1word_infrequent_query1_10points,test_1word_infrequent_query2_10points,test_2words_infrequent_query_10points
